import '../globals.css'
import Nav from '@/components/Nav'
import {getDictionary} from '@/locales/dictionaries'
import {Locale, i18n} from '@/locales'
import {Inter} from 'next/font/google'

const inter = Inter({subsets: ['latin']})

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export async function generateStaticParams(): Promise<
	{
		locale: Locale
	}[]
> {
	return i18n.locales.map((locale) => ({locale}))
}

export default async function RootLayout({
	children,
	params
}: {
	children: React.ReactNode
	params: {locale?: Locale}
}) {
	const locale: Locale = params?.locale || i18n.defaultLocale
	const dict = await getDictionary(locale)

	return (
		<html lang={locale} className="text-gray-900 leading-tight">
			<body className={[inter.className, 'min-h-screen bg-gray-100'].join(' ')}>
				<Nav locale={locale} dict={dict} />
				{children}
			</body>
		</html>
	)
}
